// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v7.34.0
// source: portfolio.proto

package portfolio

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PortfolioService_UpdateHolding_FullMethodName        = "/portfolio.PortfolioService/UpdateHolding"
	PortfolioService_GetPortfolio_FullMethodName         = "/portfolio.PortfolioService/GetPortfolio"
	PortfolioService_GetProfit_FullMethodName            = "/portfolio.PortfolioService/GetProfit"
	PortfolioService_SetPublicAmount_FullMethodName      = "/portfolio.PortfolioService/SetPublicAmount"
	PortfolioService_SetPublicMode_FullMethodName        = "/portfolio.PortfolioService/SetPublicMode"
	PortfolioService_GetMyTax_FullMethodName             = "/portfolio.PortfolioService/GetMyTax"
	PortfolioService_GetTaxList_FullMethodName           = "/portfolio.PortfolioService/GetTaxList"
	PortfolioService_CollectTax_FullMethodName           = "/portfolio.PortfolioService/CollectTax"
	PortfolioService_CollectTaxForUser_FullMethodName    = "/portfolio.PortfolioService/CollectTaxForUser"
	PortfolioService_CreateWatchlist_FullMethodName      = "/portfolio.PortfolioService/CreateWatchlist"
	PortfolioService_ListWatchlists_FullMethodName       = "/portfolio.PortfolioService/ListWatchlists"
	PortfolioService_DeleteWatchlist_FullMethodName      = "/portfolio.PortfolioService/DeleteWatchlist"
	PortfolioService_AddWatchlistItem_FullMethodName     = "/portfolio.PortfolioService/AddWatchlistItem"
	PortfolioService_RemoveWatchlistItem_FullMethodName  = "/portfolio.PortfolioService/RemoveWatchlistItem"
	PortfolioService_GetWatchlistItems_FullMethodName    = "/portfolio.PortfolioService/GetWatchlistItems"
	PortfolioService_CreateDividendPayout_FullMethodName = "/portfolio.PortfolioService/CreateDividendPayout"
	PortfolioService_GetDividendHistory_FullMethodName   = "/portfolio.PortfolioService/GetDividendHistory"
	PortfolioService_GetHoldersByListing_FullMethodName  = "/portfolio.PortfolioService/GetHoldersByListing"
)

// PortfolioServiceClient is the client API for PortfolioService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PortfolioServiceClient interface {
	UpdateHolding(ctx context.Context, in *UpdateHoldingRequest, opts ...grpc.CallOption) (*UpdateHoldingResponse, error)
	GetPortfolio(ctx context.Context, in *GetPortfolioRequest, opts ...grpc.CallOption) (*GetPortfolioResponse, error)
	GetProfit(ctx context.Context, in *GetProfitRequest, opts ...grpc.CallOption) (*GetProfitResponse, error)
	SetPublicAmount(ctx context.Context, in *SetPublicAmountRequest, opts ...grpc.CallOption) (*SetPublicAmountResponse, error)
	SetPublicMode(ctx context.Context, in *SetPublicModeRequest, opts ...grpc.CallOption) (*SetPublicModeResponse, error)
	GetMyTax(ctx context.Context, in *GetMyTaxRequest, opts ...grpc.CallOption) (*GetMyTaxResponse, error)
	GetTaxList(ctx context.Context, in *GetTaxListRequest, opts ...grpc.CallOption) (*GetTaxListResponse, error)
	CollectTax(ctx context.Context, in *CollectTaxRequest, opts ...grpc.CallOption) (*CollectTaxResponse, error)
	CollectTaxForUser(ctx context.Context, in *CollectTaxForUserRequest, opts ...grpc.CallOption) (*CollectTaxForUserResponse, error)
	// Watchlist RPCs (BE-C3-04)
	CreateWatchlist(ctx context.Context, in *CreateWatchlistRequest, opts ...grpc.CallOption) (*WatchlistResponse, error)
	ListWatchlists(ctx context.Context, in *ListWatchlistsRequest, opts ...grpc.CallOption) (*ListWatchlistsResponse, error)
	DeleteWatchlist(ctx context.Context, in *DeleteWatchlistRequest, opts ...grpc.CallOption) (*DeleteWatchlistResponse, error)
	AddWatchlistItem(ctx context.Context, in *AddWatchlistItemRequest, opts ...grpc.CallOption) (*WatchlistItemResponse, error)
	RemoveWatchlistItem(ctx context.Context, in *RemoveWatchlistItemRequest, opts ...grpc.CallOption) (*RemoveWatchlistItemResponse, error)
	GetWatchlistItems(ctx context.Context, in *GetWatchlistItemsRequest, opts ...grpc.CallOption) (*GetWatchlistItemsResponse, error)
	// Dividend RPCs (BE-C3-07)
	CreateDividendPayout(ctx context.Context, in *CreateDividendPayoutRequest, opts ...grpc.CallOption) (*DividendPayoutResponse, error)
	GetDividendHistory(ctx context.Context, in *GetDividendHistoryRequest, opts ...grpc.CallOption) (*GetDividendHistoryResponse, error)
	GetHoldersByListing(ctx context.Context, in *GetHoldersByListingRequest, opts ...grpc.CallOption) (*GetHoldersByListingResponse, error)
}

type portfolioServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPortfolioServiceClient(cc grpc.ClientConnInterface) PortfolioServiceClient {
	return &portfolioServiceClient{cc}
}

func (c *portfolioServiceClient) UpdateHolding(ctx context.Context, in *UpdateHoldingRequest, opts ...grpc.CallOption) (*UpdateHoldingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateHoldingResponse)
	err := c.cc.Invoke(ctx, PortfolioService_UpdateHolding_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *portfolioServiceClient) GetPortfolio(ctx context.Context, in *GetPortfolioRequest, opts ...grpc.CallOption) (*GetPortfolioResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPortfolioResponse)
	err := c.cc.Invoke(ctx, PortfolioService_GetPortfolio_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *portfolioServiceClient) GetProfit(ctx context.Context, in *GetProfitRequest, opts ...grpc.CallOption) (*GetProfitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProfitResponse)
	err := c.cc.Invoke(ctx, PortfolioService_GetProfit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *portfolioServiceClient) SetPublicAmount(ctx context.Context, in *SetPublicAmountRequest, opts ...grpc.CallOption) (*SetPublicAmountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetPublicAmountResponse)
	err := c.cc.Invoke(ctx, PortfolioService_SetPublicAmount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *portfolioServiceClient) SetPublicMode(ctx context.Context, in *SetPublicModeRequest, opts ...grpc.CallOption) (*SetPublicModeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetPublicModeResponse)
	err := c.cc.Invoke(ctx, PortfolioService_SetPublicMode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *portfolioServiceClient) GetMyTax(ctx context.Context, in *GetMyTaxRequest, opts ...grpc.CallOption) (*GetMyTaxResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMyTaxResponse)
	err := c.cc.Invoke(ctx, PortfolioService_GetMyTax_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *portfolioServiceClient) GetTaxList(ctx context.Context, in *GetTaxListRequest, opts ...grpc.CallOption) (*GetTaxListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTaxListResponse)
	err := c.cc.Invoke(ctx, PortfolioService_GetTaxList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *portfolioServiceClient) CollectTax(ctx context.Context, in *CollectTaxRequest, opts ...grpc.CallOption) (*CollectTaxResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CollectTaxResponse)
	err := c.cc.Invoke(ctx, PortfolioService_CollectTax_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *portfolioServiceClient) CollectTaxForUser(ctx context.Context, in *CollectTaxForUserRequest, opts ...grpc.CallOption) (*CollectTaxForUserResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CollectTaxForUserResponse)
	err := c.cc.Invoke(ctx, PortfolioService_CollectTaxForUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *portfolioServiceClient) CreateWatchlist(ctx context.Context, in *CreateWatchlistRequest, opts ...grpc.CallOption) (*WatchlistResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WatchlistResponse)
	err := c.cc.Invoke(ctx, PortfolioService_CreateWatchlist_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *portfolioServiceClient) ListWatchlists(ctx context.Context, in *ListWatchlistsRequest, opts ...grpc.CallOption) (*ListWatchlistsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListWatchlistsResponse)
	err := c.cc.Invoke(ctx, PortfolioService_ListWatchlists_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *portfolioServiceClient) DeleteWatchlist(ctx context.Context, in *DeleteWatchlistRequest, opts ...grpc.CallOption) (*DeleteWatchlistResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteWatchlistResponse)
	err := c.cc.Invoke(ctx, PortfolioService_DeleteWatchlist_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *portfolioServiceClient) AddWatchlistItem(ctx context.Context, in *AddWatchlistItemRequest, opts ...grpc.CallOption) (*WatchlistItemResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WatchlistItemResponse)
	err := c.cc.Invoke(ctx, PortfolioService_AddWatchlistItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *portfolioServiceClient) RemoveWatchlistItem(ctx context.Context, in *RemoveWatchlistItemRequest, opts ...grpc.CallOption) (*RemoveWatchlistItemResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveWatchlistItemResponse)
	err := c.cc.Invoke(ctx, PortfolioService_RemoveWatchlistItem_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *portfolioServiceClient) GetWatchlistItems(ctx context.Context, in *GetWatchlistItemsRequest, opts ...grpc.CallOption) (*GetWatchlistItemsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetWatchlistItemsResponse)
	err := c.cc.Invoke(ctx, PortfolioService_GetWatchlistItems_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *portfolioServiceClient) CreateDividendPayout(ctx context.Context, in *CreateDividendPayoutRequest, opts ...grpc.CallOption) (*DividendPayoutResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DividendPayoutResponse)
	err := c.cc.Invoke(ctx, PortfolioService_CreateDividendPayout_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *portfolioServiceClient) GetDividendHistory(ctx context.Context, in *GetDividendHistoryRequest, opts ...grpc.CallOption) (*GetDividendHistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDividendHistoryResponse)
	err := c.cc.Invoke(ctx, PortfolioService_GetDividendHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *portfolioServiceClient) GetHoldersByListing(ctx context.Context, in *GetHoldersByListingRequest, opts ...grpc.CallOption) (*GetHoldersByListingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetHoldersByListingResponse)
	err := c.cc.Invoke(ctx, PortfolioService_GetHoldersByListing_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PortfolioServiceServer is the server API for PortfolioService service.
// All implementations must embed UnimplementedPortfolioServiceServer
// for forward compatibility.
type PortfolioServiceServer interface {
	UpdateHolding(context.Context, *UpdateHoldingRequest) (*UpdateHoldingResponse, error)
	GetPortfolio(context.Context, *GetPortfolioRequest) (*GetPortfolioResponse, error)
	GetProfit(context.Context, *GetProfitRequest) (*GetProfitResponse, error)
	SetPublicAmount(context.Context, *SetPublicAmountRequest) (*SetPublicAmountResponse, error)
	SetPublicMode(context.Context, *SetPublicModeRequest) (*SetPublicModeResponse, error)
	GetMyTax(context.Context, *GetMyTaxRequest) (*GetMyTaxResponse, error)
	GetTaxList(context.Context, *GetTaxListRequest) (*GetTaxListResponse, error)
	CollectTax(context.Context, *CollectTaxRequest) (*CollectTaxResponse, error)
	CollectTaxForUser(context.Context, *CollectTaxForUserRequest) (*CollectTaxForUserResponse, error)
	// Watchlist RPCs (BE-C3-04)
	CreateWatchlist(context.Context, *CreateWatchlistRequest) (*WatchlistResponse, error)
	ListWatchlists(context.Context, *ListWatchlistsRequest) (*ListWatchlistsResponse, error)
	DeleteWatchlist(context.Context, *DeleteWatchlistRequest) (*DeleteWatchlistResponse, error)
	AddWatchlistItem(context.Context, *AddWatchlistItemRequest) (*WatchlistItemResponse, error)
	RemoveWatchlistItem(context.Context, *RemoveWatchlistItemRequest) (*RemoveWatchlistItemResponse, error)
	GetWatchlistItems(context.Context, *GetWatchlistItemsRequest) (*GetWatchlistItemsResponse, error)
	// Dividend RPCs (BE-C3-07)
	CreateDividendPayout(context.Context, *CreateDividendPayoutRequest) (*DividendPayoutResponse, error)
	GetDividendHistory(context.Context, *GetDividendHistoryRequest) (*GetDividendHistoryResponse, error)
	GetHoldersByListing(context.Context, *GetHoldersByListingRequest) (*GetHoldersByListingResponse, error)
	mustEmbedUnimplementedPortfolioServiceServer()
}

// UnimplementedPortfolioServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPortfolioServiceServer struct{}

func (UnimplementedPortfolioServiceServer) UpdateHolding(context.Context, *UpdateHoldingRequest) (*UpdateHoldingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateHolding not implemented")
}
func (UnimplementedPortfolioServiceServer) GetPortfolio(context.Context, *GetPortfolioRequest) (*GetPortfolioResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetPortfolio not implemented")
}
func (UnimplementedPortfolioServiceServer) GetProfit(context.Context, *GetProfitRequest) (*GetProfitResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProfit not implemented")
}
func (UnimplementedPortfolioServiceServer) SetPublicAmount(context.Context, *SetPublicAmountRequest) (*SetPublicAmountResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetPublicAmount not implemented")
}
func (UnimplementedPortfolioServiceServer) SetPublicMode(context.Context, *SetPublicModeRequest) (*SetPublicModeResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetPublicMode not implemented")
}
func (UnimplementedPortfolioServiceServer) GetMyTax(context.Context, *GetMyTaxRequest) (*GetMyTaxResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetMyTax not implemented")
}
func (UnimplementedPortfolioServiceServer) GetTaxList(context.Context, *GetTaxListRequest) (*GetTaxListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTaxList not implemented")
}
func (UnimplementedPortfolioServiceServer) CollectTax(context.Context, *CollectTaxRequest) (*CollectTaxResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CollectTax not implemented")
}
func (UnimplementedPortfolioServiceServer) CollectTaxForUser(context.Context, *CollectTaxForUserRequest) (*CollectTaxForUserResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CollectTaxForUser not implemented")
}
func (UnimplementedPortfolioServiceServer) CreateWatchlist(context.Context, *CreateWatchlistRequest) (*WatchlistResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateWatchlist not implemented")
}
func (UnimplementedPortfolioServiceServer) ListWatchlists(context.Context, *ListWatchlistsRequest) (*ListWatchlistsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListWatchlists not implemented")
}
func (UnimplementedPortfolioServiceServer) DeleteWatchlist(context.Context, *DeleteWatchlistRequest) (*DeleteWatchlistResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteWatchlist not implemented")
}
func (UnimplementedPortfolioServiceServer) AddWatchlistItem(context.Context, *AddWatchlistItemRequest) (*WatchlistItemResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AddWatchlistItem not implemented")
}
func (UnimplementedPortfolioServiceServer) RemoveWatchlistItem(context.Context, *RemoveWatchlistItemRequest) (*RemoveWatchlistItemResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveWatchlistItem not implemented")
}
func (UnimplementedPortfolioServiceServer) GetWatchlistItems(context.Context, *GetWatchlistItemsRequest) (*GetWatchlistItemsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetWatchlistItems not implemented")
}
func (UnimplementedPortfolioServiceServer) CreateDividendPayout(context.Context, *CreateDividendPayoutRequest) (*DividendPayoutResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateDividendPayout not implemented")
}
func (UnimplementedPortfolioServiceServer) GetDividendHistory(context.Context, *GetDividendHistoryRequest) (*GetDividendHistoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetDividendHistory not implemented")
}
func (UnimplementedPortfolioServiceServer) GetHoldersByListing(context.Context, *GetHoldersByListingRequest) (*GetHoldersByListingResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetHoldersByListing not implemented")
}
func (UnimplementedPortfolioServiceServer) mustEmbedUnimplementedPortfolioServiceServer() {}
func (UnimplementedPortfolioServiceServer) testEmbeddedByValue()                          {}

// UnsafePortfolioServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PortfolioServiceServer will
// result in compilation errors.
type UnsafePortfolioServiceServer interface {
	mustEmbedUnimplementedPortfolioServiceServer()
}

func RegisterPortfolioServiceServer(s grpc.ServiceRegistrar, srv PortfolioServiceServer) {
	// If the following call panics, it indicates UnimplementedPortfolioServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PortfolioService_ServiceDesc, srv)
}

func _PortfolioService_UpdateHolding_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateHoldingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PortfolioServiceServer).UpdateHolding(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PortfolioService_UpdateHolding_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PortfolioServiceServer).UpdateHolding(ctx, req.(*UpdateHoldingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PortfolioService_GetPortfolio_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPortfolioRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PortfolioServiceServer).GetPortfolio(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PortfolioService_GetPortfolio_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PortfolioServiceServer).GetPortfolio(ctx, req.(*GetPortfolioRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PortfolioService_GetProfit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProfitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PortfolioServiceServer).GetProfit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PortfolioService_GetProfit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PortfolioServiceServer).GetProfit(ctx, req.(*GetProfitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PortfolioService_SetPublicAmount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetPublicAmountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PortfolioServiceServer).SetPublicAmount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PortfolioService_SetPublicAmount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PortfolioServiceServer).SetPublicAmount(ctx, req.(*SetPublicAmountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PortfolioService_SetPublicMode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetPublicModeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PortfolioServiceServer).SetPublicMode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PortfolioService_SetPublicMode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PortfolioServiceServer).SetPublicMode(ctx, req.(*SetPublicModeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PortfolioService_GetMyTax_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMyTaxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PortfolioServiceServer).GetMyTax(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PortfolioService_GetMyTax_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PortfolioServiceServer).GetMyTax(ctx, req.(*GetMyTaxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PortfolioService_GetTaxList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTaxListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PortfolioServiceServer).GetTaxList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PortfolioService_GetTaxList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PortfolioServiceServer).GetTaxList(ctx, req.(*GetTaxListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PortfolioService_CollectTax_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CollectTaxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PortfolioServiceServer).CollectTax(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PortfolioService_CollectTax_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PortfolioServiceServer).CollectTax(ctx, req.(*CollectTaxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PortfolioService_CollectTaxForUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CollectTaxForUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PortfolioServiceServer).CollectTaxForUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PortfolioService_CollectTaxForUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PortfolioServiceServer).CollectTaxForUser(ctx, req.(*CollectTaxForUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PortfolioService_CreateWatchlist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateWatchlistRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PortfolioServiceServer).CreateWatchlist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PortfolioService_CreateWatchlist_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PortfolioServiceServer).CreateWatchlist(ctx, req.(*CreateWatchlistRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PortfolioService_ListWatchlists_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListWatchlistsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PortfolioServiceServer).ListWatchlists(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PortfolioService_ListWatchlists_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PortfolioServiceServer).ListWatchlists(ctx, req.(*ListWatchlistsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PortfolioService_DeleteWatchlist_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteWatchlistRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PortfolioServiceServer).DeleteWatchlist(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PortfolioService_DeleteWatchlist_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PortfolioServiceServer).DeleteWatchlist(ctx, req.(*DeleteWatchlistRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PortfolioService_AddWatchlistItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddWatchlistItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PortfolioServiceServer).AddWatchlistItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PortfolioService_AddWatchlistItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PortfolioServiceServer).AddWatchlistItem(ctx, req.(*AddWatchlistItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PortfolioService_RemoveWatchlistItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveWatchlistItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PortfolioServiceServer).RemoveWatchlistItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PortfolioService_RemoveWatchlistItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PortfolioServiceServer).RemoveWatchlistItem(ctx, req.(*RemoveWatchlistItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PortfolioService_GetWatchlistItems_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWatchlistItemsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PortfolioServiceServer).GetWatchlistItems(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PortfolioService_GetWatchlistItems_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PortfolioServiceServer).GetWatchlistItems(ctx, req.(*GetWatchlistItemsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PortfolioService_CreateDividendPayout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDividendPayoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PortfolioServiceServer).CreateDividendPayout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PortfolioService_CreateDividendPayout_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PortfolioServiceServer).CreateDividendPayout(ctx, req.(*CreateDividendPayoutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PortfolioService_GetDividendHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDividendHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PortfolioServiceServer).GetDividendHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PortfolioService_GetDividendHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PortfolioServiceServer).GetDividendHistory(ctx, req.(*GetDividendHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PortfolioService_GetHoldersByListing_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHoldersByListingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PortfolioServiceServer).GetHoldersByListing(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PortfolioService_GetHoldersByListing_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PortfolioServiceServer).GetHoldersByListing(ctx, req.(*GetHoldersByListingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PortfolioService_ServiceDesc is the grpc.ServiceDesc for PortfolioService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PortfolioService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "portfolio.PortfolioService",
	HandlerType: (*PortfolioServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateHolding",
			Handler:    _PortfolioService_UpdateHolding_Handler,
		},
		{
			MethodName: "GetPortfolio",
			Handler:    _PortfolioService_GetPortfolio_Handler,
		},
		{
			MethodName: "GetProfit",
			Handler:    _PortfolioService_GetProfit_Handler,
		},
		{
			MethodName: "SetPublicAmount",
			Handler:    _PortfolioService_SetPublicAmount_Handler,
		},
		{
			MethodName: "SetPublicMode",
			Handler:    _PortfolioService_SetPublicMode_Handler,
		},
		{
			MethodName: "GetMyTax",
			Handler:    _PortfolioService_GetMyTax_Handler,
		},
		{
			MethodName: "GetTaxList",
			Handler:    _PortfolioService_GetTaxList_Handler,
		},
		{
			MethodName: "CollectTax",
			Handler:    _PortfolioService_CollectTax_Handler,
		},
		{
			MethodName: "CollectTaxForUser",
			Handler:    _PortfolioService_CollectTaxForUser_Handler,
		},
		{
			MethodName: "CreateWatchlist",
			Handler:    _PortfolioService_CreateWatchlist_Handler,
		},
		{
			MethodName: "ListWatchlists",
			Handler:    _PortfolioService_ListWatchlists_Handler,
		},
		{
			MethodName: "DeleteWatchlist",
			Handler:    _PortfolioService_DeleteWatchlist_Handler,
		},
		{
			MethodName: "AddWatchlistItem",
			Handler:    _PortfolioService_AddWatchlistItem_Handler,
		},
		{
			MethodName: "RemoveWatchlistItem",
			Handler:    _PortfolioService_RemoveWatchlistItem_Handler,
		},
		{
			MethodName: "GetWatchlistItems",
			Handler:    _PortfolioService_GetWatchlistItems_Handler,
		},
		{
			MethodName: "CreateDividendPayout",
			Handler:    _PortfolioService_CreateDividendPayout_Handler,
		},
		{
			MethodName: "GetDividendHistory",
			Handler:    _PortfolioService_GetDividendHistory_Handler,
		},
		{
			MethodName: "GetHoldersByListing",
			Handler:    _PortfolioService_GetHoldersByListing_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "portfolio.proto",
}
